### ISSUE TITLE
Clicking on "Sign Up with STEEM" button does nothing

### ISSUE THREAD

**Issue by mightypanda-x** [BoomApps-LLC/SteemApp-Android#5]
#### Expected Behavior
Clicking on "Sign Up with STEEM" should redirect the user to steem signup page

#### Actual Behavior
Clicking on Sign Up with STEEM does nothing.

#### Steps to Reproduce
- Open the app. (Installation [Link](https://play.google.com/store/apps/details?id=com.boomapps.steemapp))
- Click on the "Sign Up with STEEM" button.

#### Possible Solution
Clicking on the button should redirect the user to https://signup.steemit.com/

#### Recording of the issue
https://www.youtube.com/watch?v=CJJZzndiSZY

Device : Samsung S8
System Operating : 8.0.0 Oreo
Browser : Google Chrome ( 66.0.3359.158 Version)
App Version: 2.0.3

**Comment by tobias-g1** [comment]
Is this an error or expected behaviour as I can see the button is set to ` android:enabled="false" `. I built the application with this enabled and seems to work as expected so wondering if there is a reason behind it currently being set to false at the moment. 

https://github.com/BoomApps-LLC/SteemApp-Android/blob/7df1f196e046287d40d38312de8956d801ec15ae/app/src/main/res/layout/activity_signin.xml#L109-L125

**Comment by yuriks2000** [comment]
Thank you both for a great research @mightypanda-x and @tobias-g1. Devs forgot to change that. Excellent that we have such great testers.

**Comment by BoomAppsLLC** [comment]
It was fixed and created pull request: https://github.com/BoomApps-LLC/SteemApp-Android/pull/23. Thank you, guys!
